version: '3'  

services: 
  mysql-db: 
    image: mysql:5
    environment: 
      MYSQL_ROOT_PASSWORD: root 
      MYSQL_DATABASE: testdb
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456
    volumes: 
      - db_data:/var/lib/mysql
    restart: always
  crud-back:
    depends_on:
      - mysql-db
    image: mehdijebali/crud-back:1.1
    ports:
      - "8080:8080"
    environment:
      DB_HOST: mysql-db:3306
      DB_USER: root
      PASSWORD: 123456

  crud-front:
    depends_on:
      - crud-back
    image: mehdijebali/crud-front:1.5
    ports:
      - "4200:4200"
    
volumes: 
  db_data: